### ISSUE TITLE
Digital Invisible Ink Stego tool

### ISSUE THREAD

**Issue by xFaraday** [JohnHammond/ctf-katana#16]
Good stego tool that I noticed wasnt in the list already.

http://diit.sourceforge.net/

**Comment by fannyhasbi** [comment]
Maybe it's better if you add it in the list and make a PR 😄

**Comment by xFaraday** [comment]
I'm sorry, im new to using github, should I just drop the issue?

**Comment by fannyhasbi** [comment]
I made a PR for you, please check #19

**Comment by xFaraday** [comment]
Thank you baby
