### ISSUE TITLE
One link is Out of Service

### ISSUE THREAD

**Issue by david-mudriy** [JohnHammond/ctf-katana#3]
-Whitespace

Tabs and spaces could be representing 1's and 0's and treating them as a binary message... or, they could be whitespace done with snow or an esoteric programming language interpreter: 
http://ws2js.luilak.net/interpreter.html<<<<<This Link Here :)

**Comment by JohnHammond** [comment]
Gotcha! Good catch, thank you for letting me. I've updated it to use TIO. https://tio.run/#whitespace
